# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 09:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onreview_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='scored_by',
            field=models.ManyToManyField(blank=True, related_name='_comment_scored_by_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='scored_by',
            field=models.ManyToManyField(blank=True, related_name='_post_scored_by_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
