# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 12:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onreview_app', '0003_auto_20160216_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='code',
            field=models.TextField(default=None, verbose_name='код'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='description',
            field=models.TextField(default=None, verbose_name='описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='onreview_app.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
