# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onreview_app', '0004_auto_20160216_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='code',
            field=models.TextField(default=None, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(default=None, verbose_name='описание'),
        ),
    ]
