# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onreview_app', '0006_auto_20160216_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='code',
            field=models.TextField(blank=True, default='', verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='описание'),
        ),
    ]
